# antimicrox
# Autogenerated from man page /usr/lib/jvm/default/man/man1/antimicrox.1.gz
complete -c antimicrox -l tray -d 'launch program in system tray only'
complete -c antimicrox -l no-tray -d 'launch program with the tray menu disabled'
complete -c antimicrox -s h -l help -d 'display this help and exit'
complete -c antimicrox -s v -l version -d 'output version information and exit'
complete -c antimicrox -l profile -d 'use specified profile as default for selected controllers'
complete -c antimicrox -l profile-controller -d 'apply configuration file to a specific controller'
complete -c antimicrox -l hidden -d 'launch program without the main window'
complete -c antimicrox -l unload -d 'unload currently enabled profile(s)'
complete -c antimicrox -l startSet -d 'start joysticks on a specific set'
complete -c antimicrox -l next -d 'Advance profile loading set options'
complete -c antimicrox -l log-level -d 'Enable logging.  Default: warn'
complete -c antimicrox -s l -l list -d 'Print information about joysticks detected by SDL'
complete -c antimicrox -l map -d 'Open game controller mapping window of selected controller'
complete -c antimicrox -l eventgen -d 'Choose between using XTest support and uinput support for event generation'

