# aubiocut
# Autogenerated from man page /usr/lib/jvm/default/man/man1/aubiocut.1.gz
complete -c aubiocut -s i -l input -d 'Run analysis on this audio file'
complete -c aubiocut -s r -l samplerate -d 'Fetch the input source, resampled at the given sampling rate'
complete -c aubiocut -s B -l bufsize -d 'The size of the buffer to analyze, that is the length of the window used for …'
complete -c aubiocut -s H -l hopsize -d 'The number of samples between two consecutive analysis.  Defaults to 256'
complete -c aubiocut -s O -l onset -d 'The onset detection method to use.  See ONSET METHODS below'
complete -c aubiocut -s b -l beat -d 'Use beat locations instead of onset locations'
complete -c aubiocut -s t -l onset-threshold -d 'Set the threshold value for the onset peak picking'
complete -c aubiocut -s c -l cut -d 'Cut input sound file at detected labels'
complete -c aubiocut -s o -l output -d 'Specify the directory path where slices of the original source should be crea…'
complete -c aubiocut -l cut-until-nsamples -d 'How many extra samples should be added at the end of each slice (default 0)'
complete -c aubiocut -l cut-until-nslices -d 'How many extra slices should be added at the end of each slice (default 0)'
complete -c aubiocut -l create-first -d 'Alway create first slice'
complete -c aubiocut -s h -l help -d 'Print a short help message and exit'
complete -c aubiocut -s v -l verbose -d 'Be verbose'
complete -c aubiocut -s q -l quiet -d 'Be quiet.  ONSET METHODS'

