# aubiopitch
# Autogenerated from man page /usr/lib/jvm/default/man/man1/aubiopitch.1.gz
complete -c aubiopitch -s i -l input -d 'Run analysis on this audio file'
complete -c aubiopitch -s o -l output -d 'Save results in this file'
complete -c aubiopitch -s r -l samplerate -d 'Fetch the input source, resampled at the given sampling rate'
complete -c aubiopitch -s B -l bufsize -d 'The size of the buffer to analyze, that is the length of the window used for …'
complete -c aubiopitch -s H -l hopsize -d 'The number of samples between two consecutive analysis.  Defaults to 256'
complete -c aubiopitch -s p -l pitch -d 'The pitch detection method to use.  See PITCH METHODS below'
complete -c aubiopitch -s u -l pitch-unit -d 'The unit to be used to print frequencies'
complete -c aubiopitch -s l -l pitch-tolerance -d 'Set the tolerance for the pitch detection algorithm'
complete -c aubiopitch -s s -l silence -d 'Set the silence threshold, in dB, under which the onset will not be detected'
complete -c aubiopitch -s T -l timeformat -d 'Set time format (samples, ms, seconds).  Defaults to seconds'
complete -c aubiopitch -s m -l mix-input -d 'Mix source signal to the output signal before writing to sink'
complete -c aubiopitch -s f -l force-overwrite -d 'Overwrite output file if it already exists'
complete -c aubiopitch -s j -l jack -d 'Use Jack input/output'
complete -c aubiopitch -s h -l help -d 'Print a short help message and exit'
complete -c aubiopitch -s v -l verbose -d 'Be verbose.  PITCH METHODS'

