# aubioquiet
# Autogenerated from man page /usr/lib/jvm/default/man/man1/aubioquiet.1.gz
complete -c aubioquiet -s i -l input -d 'Run analysis on this audio file'
complete -c aubioquiet -s r -l samplerate -d 'Fetch the input source, resampled at the given sampling rate'
complete -c aubioquiet -s B -l bufsize -d 'The size of the buffer to analyze, that is the length of the window used for …'
complete -c aubioquiet -s H -l hopsize -d 'The number of samples between two consecutive analysis.  Defaults to 256'
complete -c aubioquiet -s s -l silence -d 'Set the silence threshold, in dB, under which the pitch will not be detected'
complete -c aubioquiet -s T -l timeformat -d 'Set time format (samples, ms, seconds).  Defaults to seconds'
complete -c aubioquiet -s h -l help -d 'Print a short help message and exit'
complete -c aubioquiet -s v -l verbose -d 'Be verbose.  EXAMPLE OUTPUT'

