# aubionotes
# Autogenerated from man page /usr/lib/jvm/default/man/man1/aubionotes.1.gz
complete -c aubionotes -s i -l input -d 'Run analysis on this audio file'
complete -c aubionotes -s r -l samplerate -d 'Fetch the input source, resampled at the given sampling rate'
complete -c aubionotes -s B -l bufsize -d 'The size of the buffer to analyze, that is the length of the window used for …'
complete -c aubionotes -s H -l hopsize -d 'The number of samples between two consecutive analysis.  Defaults to 256'
complete -c aubionotes -s O -l onset -d 'The onset detection method to use.  See ONSET METHODS below'
complete -c aubionotes -s t -l onset-threshold -d 'Set the threshold value for the onset peak picking'
complete -c aubionotes -s M -l minioi -d 'Set the minimum inter-onset interval, in seconds, the shortest interval betwe…'
complete -c aubionotes -s p -l pitch -d 'The pitch detection method to use.  See PITCH METHODS below'
complete -c aubionotes -s u -l pitch-unit -d 'The unit to be used to print frequencies'
complete -c aubionotes -s l -l pitch-tolerance -d 'Set the tolerance for the pitch detection algorithm'
complete -c aubionotes -s s -l silence -d 'Set the silence threshold, in dB, under which the pitch will not be detected'
complete -c aubionotes -s d -l release-drop -d 'Set the release drop threshold, in dB'
complete -c aubionotes -s T -l timeformat -d 'Set time format (samples, ms, seconds).  Defaults to seconds'
complete -c aubionotes -s j -l jack -d 'Use Jack input/output'
complete -c aubionotes -s h -l help -d 'Print a short help message and exit'
complete -c aubionotes -s v -l verbose -d 'Be verbose.  ONSET METHODS'

