# gig2stereo
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gig2stereo.1.gz
complete -c gig2stereo -l force-replace -d 'Force replacing any found old mono sample reference by the new true stereo sa…'
complete -c gig2stereo -l incompatible -d 'Also match incompatible mono samples as pairs'
complete -c gig2stereo -l keep -d 'Keep old mono samples'
complete -c gig2stereo -s r -d 'Recurse through subdirectories'
complete -c gig2stereo -s v -d 'Print version and exit'

