# glacier2router
# Autogenerated from man page /usr/lib/jvm/default/man/man1/glacier2router.1.gz
complete -c glacier2router -s h -l help -d 'br Displays help message'
complete -c glacier2router -s v -l version -d 'Displays the Ice version'
complete -c glacier2router -l nowarn -d 'br Suppress warnings'
complete -c glacier2router -l daemon -d 'br Run as a daemon'
complete -c glacier2router -l pidfile -d 'br Write process ID into FILE'
complete -c glacier2router -l noclose -d 'br Do not close open file descriptors'
complete -c glacier2router -l nochdir

