# gnuchess
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gnuchess.1.gz
complete -c gnuchess -s h -l help -d 'display this help and exit'
complete -c gnuchess -s v -l version -d 'display version information and exit'
complete -c gnuchess -s q -l quiet -d 'make the program silent on startup'
complete -c gnuchess -l silent -d 'same as -q'
complete -c gnuchess -s x -l xboard -d 'start in engine mode'
complete -c gnuchess -s p -l post -d 'start up showing thinking'
complete -c gnuchess -s e -l easy -d 'disable thinking in opponents time'
complete -c gnuchess -s m -l manual -d 'enable manual mode'
complete -c gnuchess -s u -l uci -d 'enable UCI protocol (externally behave as UCI engine)'
complete -c gnuchess -s M -l memory -d 'specify memory usage in MB for hashtable'
complete -c gnuchess -s a -l addbook -d 'compile book. bin from pgn book \'filename\''
complete -c gnuchess -s g -l graphic -d 'enable graphic mode'

