# gst-device-monitor-1
# Autogenerated from man page /usr/share/man/man1/gst-device-monitor-1.0.1.gz
complete -c gst-device-monitor-1 -s i -l include-hidden -d 'Include devices from hidden device providers'

