# icebox
# Autogenerated from man page /usr/lib/jvm/default/man/man1/icebox.1.gz
complete -c icebox -s h -l help -d 'br Displays a help message'
complete -c icebox -s v -l version -d 'Displays the Ice version'
complete -c icebox -l nowarn -d 'br Suppress warnings'
complete -c icebox -l daemon -d 'br Run as a daemon'
complete -c icebox -l pidfile -d 'br Write process ID into FILE'
complete -c icebox -l noclose -d 'br Do not close open file descriptors'
complete -c icebox -l nochdir

