# iceboxadmin
# Autogenerated from man page /usr/lib/jvm/default/man/man1/iceboxadmin.1.gz
complete -c iceboxadmin -s h -l help -d 'br Displays a help message'
complete -c iceboxadmin -s v -l version -d 'Displays the Ice version'

