# icebridge
# Autogenerated from man page /usr/lib/jvm/default/man/man1/icebridge.1.gz
complete -c icebridge -s h -l help -d 'br Displays help message'
complete -c icebridge -s v -l version -d 'Displays the Ice version'
complete -c icebridge -l daemon -d 'br Run as a daemon'
complete -c icebridge -l pidfile -d 'br Write process ID into FILE'
complete -c icebridge -l noclose -d 'br Do not close open file descriptors'
complete -c icebridge -l nochdir

