# icegriddb
# Autogenerated from man page /usr/lib/jvm/default/man/man1/icegriddb.1.gz
complete -c icegriddb -s h -l help -d 'br Show program help'
complete -c icegriddb -s v -l version -d 'br Display the Ice version'
complete -c icegriddb -l import -d 'br Import database from the specifed file'
complete -c icegriddb -l export -d 'br Export database to the specified file'
complete -c icegriddb -l dbpath -d 'br Source or target database environment'
complete -c icegriddb -l mapsize -d 'br Set LMDB map size in MB (optional, import only)'
complete -c icegriddb -l server-version -d 'br Set Ice version for IceGrid servers (optional, import only)'
complete -c icegriddb -s d -l debug

