# icegridregistry
# Autogenerated from man page /usr/lib/jvm/default/man/man1/icegridregistry.1.gz
complete -c icegridregistry -s h -l help -d 'br Displays a help message'
complete -c icegridregistry -s v -l version -d 'Displays the Ice version'
complete -c icegridregistry -l daemon -d 'br Run as a daemon'
complete -c icegridregistry -l pidfile -d 'br Write process ID into FILE'
complete -c icegridregistry -l noclose -d 'br Do not close open file descriptors'
complete -c icegridregistry -l nochdir -d 'br Do not change the current working directory'
complete -c icegridregistry -l nowarn -d 'br Do not print security warnings'
complete -c icegridregistry -l readonly
complete -c icegridregistry -l initdb-from-replica

