# icegridadmin
# Autogenerated from man page /usr/lib/jvm/default/man/man1/icegridadmin.1.gz
complete -c icegridadmin -s h -l help -d 'br Show program help'
complete -c icegridadmin -s v -l version -d 'br Display the Ice version'
complete -c icegridadmin -s e -d 'br Execute COMMANDS'
complete -c icegridadmin -s d -l debug -d 'br Print debug messages'
complete -c icegridadmin -s s -l server -d 'br Start icegridadmin as a server (to parse XML files)'
complete -c icegridadmin -s i -l instanceName -d 'br Connect to the registry with the given instance name'
complete -c icegridadmin -s H -l host -d 'br Connect to the registry at the given host'
complete -c icegridadmin -s P -l port -d 'br Connect to the registry running on the given port'
complete -c icegridadmin -s u -l username -d 'br Login with the given username'
complete -c icegridadmin -s p -l password -d 'br Login with the given password'
complete -c icegridadmin -s S -l ssl -d 'br Authenticate through SSL'
complete -c icegridadmin -s r -l replica

