# icegridnode
# Autogenerated from man page /usr/lib/jvm/default/man/man1/icegridnode.1.gz
complete -c icegridnode -s h -l help -d 'br Displays help message'
complete -c icegridnode -s v -l version -d 'Displays the Ice version'
complete -c icegridnode -l daemon -d 'br Run as a daemon'
complete -c icegridnode -l pidfile -d 'br Write process ID into FILE'
complete -c icegridnode -l noclose -d 'br Do not close open file descriptors'
complete -c icegridnode -l nochdir -d 'br Do not change the current working directory'
complete -c icegridnode -l nowarn -d 'br Do not print security warnings'
complete -c icegridnode -l readonly -d 'br Start the collocated master registry in read-only mode'
complete -c icegridnode -l initdb-from-replica -d 'br Initialize the collocated registry database from the given replica'
complete -c icegridnode -l deploy

