# icepatch2server
# Autogenerated from man page /usr/lib/jvm/default/man/man1/icepatch2server.1.gz
complete -c icepatch2server -s h -l help -d 'br Displays a help message'
complete -c icepatch2server -s v -l version -d 'Displays the Ice version'
complete -c icepatch2server -l daemon -d 'br Run as a daemon'
complete -c icepatch2server -l pidfile -d 'br Write process ID into FILE'
complete -c icepatch2server -l noclose -d 'br Do not close open file descriptors'
complete -c icepatch2server -l nochdir

