# icepatch2client
# Autogenerated from man page /usr/lib/jvm/default/man/man1/icepatch2client.1.gz
complete -c icepatch2client -s h -l help -d 'br Displays help message'
complete -c icepatch2client -s v -l version -d 'Displays the Ice version'
complete -c icepatch2client -s t -l thorough

