# icepatch2calc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/icepatch2calc.1.gz
complete -c icepatch2calc -s h -l help -d 'br Displays a help message'
complete -c icepatch2calc -s v -l version -d 'Displays the Ice version'
complete -c icepatch2calc -s z -l compress -d 'br Normally, icepatch2calc scans the data directory and compresses a file onl…'
complete -c icepatch2calc -s Z -l no-compress -d 'br This option allows you to create a client-side checksum file'
complete -c icepatch2calc -s i -l case-insensitive -d 'br This option disallows file names that differ only in case'
complete -c icepatch2calc -s V -l verbose

