# icestormdb
# Autogenerated from man page /usr/lib/jvm/default/man/man1/icestormdb.1.gz
complete -c icestormdb -s h -l help -d 'br Show program help'
complete -c icestormdb -s v -l version -d 'br Display the Ice version'
complete -c icestormdb -l import -d 'br Import database from the specifed file'
complete -c icestormdb -l export -d 'br Export database to the specified file'
complete -c icestormdb -l dbpath -d 'br Source or target database environment'
complete -c icestormdb -l mapsize -d 'br Set LMDB map size in MB (optional, import only)'
complete -c icestormdb -s d -l debug

