# icestormadmin
# Autogenerated from man page /usr/lib/jvm/default/man/man1/icestormadmin.1.gz
complete -c icestormadmin -s h -l help -d 'br Displays a help message'
complete -c icestormadmin -s v -l version -d 'Displays the Ice version'
complete -c icestormadmin -s e -d 'br Execute COMMANDS'
complete -c icestormadmin -s d -l debug

