# inotifywatch
# Autogenerated from man page /usr/lib/jvm/default/man/man1/inotifywatch.1.gz
complete -c inotifywatch -s h -l help -d 'Output some helpful usage information'
complete -c inotifywatch -s v -l verbose -d 'Output some extra information on standard error during execution'
complete -c inotifywatch -l fromfile -d 'Read filenames to watch or exclude from a file, one filename per line'
complete -c inotifywatch -s z -l zero -d 'Output table rows and columns even if all elements are zero'
complete -c inotifywatch -l exclude -d 'Do not process any events for the subset of files whose filenames match the s…'
complete -c inotifywatch -l excludei -d 'Do not process any events for the subset of files whose filenames match the s…'
complete -c inotifywatch -l include -d 'Process events only for the subset of files whose filenames match the specifi…'
complete -c inotifywatch -l includei -d 'Process events only for the subset of files whose filenames match the specifi…'
complete -c inotifywatch -s r -l recursive -d 'Watch all subdirectories of any directories passed as arguments'
complete -c inotifywatch -s P -l no-dereference -d 'Do not follow symlinks'
complete -c inotifywatch -s t -l timeout -d 'Listen only for the specified amount of seconds'
complete -c inotifywatch -s e -l event -d 'Listen for specific event(s) only'
complete -c inotifywatch -s a -l ascending -d 'Sort output ascending by event counts for the specified event'
complete -c inotifywatch -s d -d options
complete -c inotifywatch -l descending -d 'Sort output descending by event counts for the specified event'
complete -c inotifywatch -s I -l inotify -d 'Watch using inotify'
complete -c inotifywatch -s F -l fanotify -d 'Watch using fanotify (default)'
complete -c inotifywatch -s S -l filesystem -d 'Watch entire filesystem of any directories passed as arguments using fanotify'

