# kpseaccess
# Autogenerated from man page /usr/lib/jvm/default/man/man1/kpseaccess.1.gz
complete -c kpseaccess -l help -d 'Print help message and exit'
complete -c kpseaccess -l version -d 'Print version information and exit'

