# lmms
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lmms.1.gz
complete -c lmms -l geometry -d 'Specify the prefered size and position of the main window'
complete -c lmms -s c -l config -d 'Get the configuration from configfile instead of ~/. lmmsrc. xml (default)'
complete -c lmms -s h -l help -d 'Show usage information and exit'
complete -c lmms -s v -l version -d 'Show version information and exit'
complete -c lmms -s a -l float -d 'Use 32bit float bit depth'
complete -c lmms -s b -l bitrate -d 'Specify output bitrate in KBit/s (for OGG encoding only), default is 160'
complete -c lmms -s f -l format -d 'Specify format of render-output where format is either \'wav\', \'ogg\' or \'mp3\''
complete -c lmms -s i -l interpolation -d 'Specify interpolation method - possible values are linear, sincfastest (defau…'
complete -c lmms -s l -l loop -d 'Render the given file as a loop, i. e'
complete -c lmms -s m -l mode -d 'Set the stereo mode used for the MP3 export'
complete -c lmms -s o -l output -d 'Render into path'
complete -c lmms -s p -l profile -d 'Dump profiling information to file out'
complete -c lmms -s s -l samplerate -d 'Specify output samplerate in Hz - range is 44100 (default) to 192000'
complete -c lmms -s x -l oversampling -d 'Specify oversampling, possible values: 1, 2 (default), 4, 8'

