# murmurd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/murmurd.1.gz
complete -c murmurd -s h -o help -l help -d 'Show a summary of the options'
complete -c murmurd -o ini -d 'Specify which ini file to use'
complete -c murmurd -o fg -d 'Run in the foreground (do not fork)'
complete -c murmurd -s v -d 'Verbose mode, slightly more information is logged'
complete -c murmurd -o supw -d 'This sets the SuperUser password for a server'
complete -c murmurd -o readsupw -d 'Reads SuperUser password from stdin'
complete -c murmurd -o disablesu -d 'Disables the SuperUser account'
complete -c murmurd -o limits -d 'Tests and shows how many file descriptors and threads can be created'
complete -c murmurd -o wipessl -d 'Remove SSL certificates from database'
complete -c murmurd -o wipelogs -d 'Remove all log entries from database'
complete -c murmurd -o loggroups -d 'Turns on logging for group changes for all servers'
complete -c murmurd -o logacls -d 'Turns on logging for ACL changes for all servers'
complete -c murmurd -o license -d 'Show Murmur\'s license'
complete -c murmurd -o authors -d 'Show Murmur\'s authors'
complete -c murmurd -o third-party-licenses -d 'Show licenses for third-party software used by Murmur'
complete -c murmurd -o version -l version -d 'Show version information.  SIGNALS'

