# murmur-user-wrapper
# Autogenerated from man page /usr/lib/jvm/default/man/man1/murmur-user-wrapper.1.gz
complete -c murmur-user-wrapper -s d -d 'Set directory to use.  By default, the wrapper script uses $HOME/murmur'
complete -c murmur-user-wrapper -s s -d 'Check if murmur process is running'
complete -c murmur-user-wrapper -s k -d 'Terminate running murmur process'
complete -c murmur-user-wrapper -s i -d 'Initialize only, do not start the server'
complete -c murmur-user-wrapper -s p -d 'Specify password for the SuperUser account and exit'

