# podofotxt2pdf
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podofotxt2pdf.1.gz
complete -c podofotxt2pdf -o fontname -d 'Use the font <name>'
complete -c podofotxt2pdf -o utf8 -d 'specifies that the input text is UTF8 encoded instead of Windows ANSI encoding'

