# podofopages
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podofopages.1.gz
complete -c podofopages -l delete -d 'Deletes the page NUMBER (number is 0-based)'
complete -c podofopages -l move -d 'Moves a page FROM TO in the document (FROM and TO are 0-based)'

