# podofoencrypt
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podofoencrypt.1.gz
complete -c podofoencrypt -l help
complete -c podofoencrypt -l rc4v1
complete -c podofoencrypt -l rc4v2
complete -c podofoencrypt -l aes
complete -c podofoencrypt -s u
complete -c podofoencrypt -s o
complete -c podofoencrypt -l print -d 'Allow printing the document'
complete -c podofoencrypt -l edit -d 'Allow modification of the document besides annotations, form fields or changi…'
complete -c podofoencrypt -l copy -d 'Allow extraction of text and graphics'
complete -c podofoencrypt -l editnotes -d 'Add or modify text annotations or form fields (if ePdfPermissions_Edit is set…'
complete -c podofoencrypt -l fillandsign -d 'Fill in existing form or signature fields'
complete -c podofoencrypt -l accessible -d 'Extract text and graphics to support user with disabillities'
complete -c podofoencrypt -l assemble -d 'Assemble the document: insert, create, rotate delete pages or add bookmarks'
complete -c podofoencrypt -l highprint -d 'Print a high resolution version of the document'

