# ppscheck
# Autogenerated from man page /usr/lib/jvm/default/man/man8/ppscheck.8.gz
complete -c ppscheck -o '?+'
complete -c ppscheck -o m+
complete -c ppscheck -o p+
complete -c ppscheck -o V+
complete -c ppscheck -s x -l seconds

