# rifftree
# Autogenerated from man page /usr/lib/jvm/default/man/man1/rifftree.1.gz
complete -c rifftree -s v -d 'Print version and exit'
complete -c rifftree -s s -d 'Print the size of each RIFF chunk'
complete -c rifftree -l flat -d 'First chunk of file is not a list (container) chunk'
complete -c rifftree -l first-chunk-id -d 'Currently only used in combination with --flat'
complete -c rifftree -l big-endian -d 'File is in big endian format.  Currently only used in combination with --flat'
complete -c rifftree -l little-endian -d 'endian type of your machine will be used by default'

