# rmiregistry-openjdk18
# Autogenerated from man page /usr/lib/jvm/default/man/man1/rmiregistry-openjdk18.1.gz
complete -c rmiregistry-openjdk18 -o Joption -d 'Used with any Java option to pass the option following the'
complete -c rmiregistry-openjdk18 -s J -s J -d 'Java interpreter'

