# slice2html
# Autogenerated from man page /usr/lib/jvm/default/man/man1/slice2html.1.gz
complete -c slice2html -s h -l help -d 'br Displays help message'
complete -c slice2html -s v -l version -d 'Displays the compiler version'
complete -c slice2html -o DNAME -d 'br Defines the preprocessor symbol NAME'
complete -c slice2html -o UNAME -d 'br Undefines the preprocessor symbol NAME'
complete -c slice2html -o IDIR -d 'br Add the directory DIR to the search path for #include directives'
complete -c slice2html -s E -d 'br Print the preprocessor output on stdout'
complete -c slice2html -l output-dir -d 'br Place the generated files into directory DIR'
complete -c slice2html -s d -l debug -d 'br Print debug information showing the operation of the Slice parser'
complete -c slice2html -l hdr -d 'br Prepend FILE to each generated HTML file (except for _sindex. html)'
complete -c slice2html -l ftr -d 'br Append FILE to each generated HTML file (except for _sindex. html)'
complete -c slice2html -l indexhdr -d 'br slice2html generates a file _sindex'
complete -c slice2html -l indexftr -d 'br Append FILE to the generated sindex. html page'
complete -c slice2html -l image-dir -d 'br With this option, slice2html looks in the specified directory for images t…'
complete -c slice2html -l logo-url -d 'br Use the specified URL as a hyperlink for the company logo that is added to…'
complete -c slice2html -l search -d 'br If this option is specified, the generated pages contain a search box that…'
complete -c slice2html -l index -d 'br slice2html generates sub-indexes for various Slice symbols'
complete -c slice2html -l summary

