# slice2swift
# Autogenerated from man page /usr/lib/jvm/default/man/man1/slice2swift.1.gz
complete -c slice2swift -s h -l help -d 'br Displays a help message'
complete -c slice2swift -s v -l version -d 'Displays the compiler version'
complete -c slice2swift -o DNAME -d 'br Defines the preprocessor symbol NAME'
complete -c slice2swift -o UNAME -d 'br Undefines the preprocessor symbol NAME'
complete -c slice2swift -o IDIR -d 'br Add the directory DIR to the search path for #include directives'
complete -c slice2swift -s E -d 'br Print the preprocessor output on stdout'
complete -c slice2swift -l output-dir -d 'br Place the generated files into directory DIR'
complete -c slice2swift -s d -l debug -d 'br Print debug information showing the operation of the Slice parser'
complete -c slice2swift -l depend -d 'br Print dependency information to standard output by default, or to the file…'
complete -c slice2swift -l depend-xml -d 'br Print dependency information in XML format to standard output by default, …'
complete -c slice2swift -l depend-file -d 'br Directs dependency information to the specified file'
complete -c slice2swift -l validate

