# slice2js
# Autogenerated from man page /usr/lib/jvm/default/man/man1/slice2js.1.gz
complete -c slice2js -s h -l help -d 'br Displays help message'
complete -c slice2js -s v -l version -d 'Displays the compiler version'
complete -c slice2js -o DNAME -d 'br Defines the preprocessor symbol NAME'
complete -c slice2js -o UNAME -d 'br Undefines the preprocessor symbol NAME'
complete -c slice2js -o IDIR -d 'br Add the directory DIR to the search path for #include directives'
complete -c slice2js -s E -d 'br Print the preprocessor output on stdout'
complete -c slice2js -l output-dir -d 'br Place the generated files into directory DIR'
complete -c slice2js -s d -l debug -d 'br Print debug information showing the operation of the Slice parser'
complete -c slice2js -l depend -d 'br Print dependency information to standard output by default, or to the file…'
complete -c slice2js -l depend-xml -d 'br Print dependency information in XML format to standard output by default, …'
complete -c slice2js -l depend-file -d 'br Directs dependency information to the specified file'
complete -c slice2js -l depend-json -d 'br Print dependency information in JSON format to standard output by default,…'
complete -c slice2js -l validate -d 'br Checks the provided command-line options for correctness, and does not gen…'
complete -c slice2js -l stdout -d 'br Print generated code to standard output'
complete -c slice2js -l typescript

