# slice2java
# Autogenerated from man page /usr/lib/jvm/default/man/man1/slice2java.1.gz
complete -c slice2java -s h -l help -d 'br Displays a help message'
complete -c slice2java -s v -l version -d 'Displays the compiler version'
complete -c slice2java -o DNAME -d 'br Defines the preprocessor symbol NAME'
complete -c slice2java -o UNAME -d 'br Undefines the preprocessor symbol NAME'
complete -c slice2java -o IDIR -d 'br Add the directory DIR to the search path for #include directives'
complete -c slice2java -s E -d 'br Print the preprocessor output on stdout'
complete -c slice2java -l output-dir -d 'br Place the generated files into directory DIR'
complete -c slice2java -s d -l debug -d 'br Print debug information showing the operation of the Slice parser'
complete -c slice2java -l depend -d 'br Print dependency information to standard output by default, or to the file…'
complete -c slice2java -l depend-xml -d 'br Print dependency information in XML format to standard output by default, …'
complete -c slice2java -l depend-file -d 'br Directs dependency information to the specified file'
complete -c slice2java -l validate -d 'br Checks the provided command-line options for correctness, and does not gen…'
complete -c slice2java -l compat -d 'br Generate code for the Java Compat mapping'
complete -c slice2java -l tie -d 'br Generate tie classes.  (Java Compat only)'
complete -c slice2java -l impl -d 'br Generate sample implementation files'
complete -c slice2java -l impl-tie -d 'br Generate sample implementation files using tie classes'
complete -c slice2java -l checksum -d 'br Generate checksums for Slice definitions into the class CLASS'
complete -c slice2java -l meta -d 'br Define the file metadata directive META'
complete -c slice2java -l list-generated

