# slice2cpp
# Autogenerated from man page /usr/lib/jvm/default/man/man1/slice2cpp.1.gz
complete -c slice2cpp -s h -l help -d 'br Displays help message'
complete -c slice2cpp -s v -l version -d 'Displays the compiler version'
complete -c slice2cpp -o DNAME -d 'br Defines the preprocessor symbol NAME'
complete -c slice2cpp -o UNAME -d 'br Undefines the preprocessor symbol NAME'
complete -c slice2cpp -o IDIR -d 'br Add the directory DIR to the search path for #include directives'
complete -c slice2cpp -s E -d 'br Print the preprocessor output on stdout'
complete -c slice2cpp -l output-dir -d 'br Place the generated files into directory DIR'
complete -c slice2cpp -s d -l debug -d 'br Print debug information showing the operation of the Slice parser'
complete -c slice2cpp -l depend -d 'br Print dependency information to standard output by default, or to the file…'
complete -c slice2cpp -l depend-xml -d 'br Print dependency information in XML format to standard output by default, …'
complete -c slice2cpp -l depend-file -d 'br Directs dependency information to the specified file'
complete -c slice2cpp -l validate -d 'br Checks the provided command-line options for correctness, and does not gen…'
complete -c slice2cpp -l header-ext -d 'br Changes the file extension for the generated header files from the default…'
complete -c slice2cpp -l source-ext -d 'br Changes the file extension for the generated source files from the default…'
complete -c slice2cpp -l add-header -d 'br This option adds an include directive for the specified header at the begi…'
complete -c slice2cpp -l include-dir -d 'br Modifies #include directives in source files to prepend the path name of e…'
complete -c slice2cpp -l impl-c++11 -d 'br Generate sample implementation files for the C++11 mapping'
complete -c slice2cpp -l impl-c++98 -d 'br Generate sample implementation files for the C++98 mapping'
complete -c slice2cpp -l checksum

